<?php
// phpcs:ignoreFile
/**
 * @file
 * A database agnostic dump for testing purposes.
 *
 * This file was generated by the Drupal 9.5.3-dev db-tools.php script.
 */

use Drupal\Core\Database\Database;

$connection = Database::getConnection();
// Ensure any tables with a serial column with a value of 0 are created as
// expected.
if ($connection->databaseType() === 'mysql') {
  $sql_mode = $connection->query("SELECT @@sql_mode;")->fetchField();
  $connection->query("SET sql_mode = '$sql_mode,NO_AUTO_VALUE_ON_ZERO'");
}

$connection->schema()->createTable('file_managed', array(
  'fields' => array(
    'fid' => array(
      'type' => 'serial',
      'not null' => TRUE,
      'size' => 'normal',
      'unsigned' => TRUE,
    ),
    'uid' => array(
      'type' => 'int',
      'not null' => TRUE,
      'size' => 'normal',
      'default' => '0',
      'unsigned' => TRUE,
    ),
    'filename' => array(
      'type' => 'varchar',
      'not null' => TRUE,
      'length' => '255',
      'default' => '',
    ),
    'uri' => array(
      'type' => 'varchar',
      'not null' => TRUE,
      'length' => '255',
      'default' => '',
      'binary' => TRUE,
    ),
    'filemime' => array(
      'type' => 'varchar',
      'not null' => TRUE,
      'length' => '255',
      'default' => '',
    ),
    'filesize' => array(
      'type' => 'int',
      'not null' => TRUE,
      'size' => 'big',
      'default' => '0',
      'unsigned' => TRUE,
    ),
    'status' => array(
      'type' => 'int',
      'not null' => TRUE,
      'size' => 'tiny',
      'default' => '0',
    ),
    'timestamp' => array(
      'type' => 'int',
      'not null' => TRUE,
      'size' => 'normal',
      'default' => '0',
      'unsigned' => TRUE,
    ),
  ),
  'primary key' => array(
    'fid',
  ),
  'unique keys' => array(
    'uri' => array(
      'uri',
    ),
  ),
  'indexes' => array(
    'uid' => array(
      'uid',
    ),
    'status' => array(
      'status',
    ),
    'timestamp' => array(
      'timestamp',
    ),
  ),
  'mysql_character_set' => 'utf8',
));

$connection->insert('file_managed')
->fields(array(
  'fid',
  'uid',
  'filename',
  'uri',
  'filemime',
  'filesize',
  'status',
  'timestamp',
))
->values(array(
  'fid' => '1',
  'uid' => '1',
  'filename' => '1-1-6.jpg',
  'uri' => 'public://2023-01/1-1-6.jpg',
  'filemime' => 'image/jpeg',
  'filesize' => '968107',
  'status' => '1',
  'timestamp' => '1674979675',
))
->values(array(
  'fid' => '2',
  'uid' => '1',
  'filename' => '2M9A0271 - Turimetta Beach Sunrise.jpg',
  'uri' => 'public://2023-01/2M9A0271 - Turimetta Beach Sunrise.jpg',
  'filemime' => 'image/jpeg',
  'filesize' => '803115',
  'status' => '1',
  'timestamp' => '1674979710',
))
->values(array(
  'fid' => '3',
  'uid' => '1',
  'filename' => '2M9A0287.jpg',
  'uri' => 'public://2023-01/2M9A0287.jpg',
  'filemime' => 'image/jpeg',
  'filesize' => '658671',
  'status' => '1',
  'timestamp' => '1674979724',
))
->values(array(
  'fid' => '4',
  'uid' => '1',
  'filename' => '1962_Facel_Vega_Facel_II_UK_spec_classic_supercar__fs_2048x1536.jpg',
  'uri' => 'public://2023-01/1962_Facel_Vega_Facel_II_UK_spec_classic_supercar__fs_2048x1536.jpg',
  'filemime' => 'image/jpeg',
  'filesize' => '986579',
  'status' => '1',
  'timestamp' => '1674979755',
))
->values(array(
  'fid' => '5',
  'uid' => '1',
  'filename' => '10425528_10152432673336246_6977313381040041490_n.jpg',
  'uri' => 'public://2023-01/10425528_10152432673336246_6977313381040041490_n.jpg',
  'filemime' => 'image/jpeg',
  'filesize' => '114187',
  'status' => '1',
  'timestamp' => '1674979791',
))
->values(array(
  'fid' => '6',
  'uid' => '1',
  'filename' => '20211116_115601.jpg',
  'uri' => 'public://2023-01/20211116_115601.jpg',
  'filemime' => 'image/jpeg',
  'filesize' => '31951',
  'status' => '1',
  'timestamp' => '1674979825',
))
->execute();

// Reset the SQL mode.
if ($connection->databaseType() === 'mysql') {
  $connection->query("SET sql_mode = '$sql_mode'");
}