<?php
// phpcs:ignoreFile
/**
 * @file
 * A database agnostic dump for testing purposes.
 *
 * This file was generated by the Drupal 9.5.3-dev db-tools.php script.
 */

use Drupal\Core\Database\Database;

$connection = Database::getConnection();
// Ensure any tables with a serial column with a value of 0 are created as
// expected.
if ($connection->databaseType() === 'mysql') {
  $sql_mode = $connection->query("SELECT @@sql_mode;")->fetchField();
  $connection->query("SET sql_mode = '$sql_mode,NO_AUTO_VALUE_ON_ZERO'");
}

$connection->schema()->createTable('variable', array(
  'fields' => array(
    'name' => array(
      'type' => 'varchar',
      'not null' => TRUE,
      'length' => '128',
      'default' => '',
    ),
    'value' => array(
      'type' => 'blob',
      'not null' => TRUE,
      'size' => 'big',
    ),
  ),
  'primary key' => array(
    'name',
  ),
  'mysql_character_set' => 'utf8',
));

$connection->insert('variable')
->fields(array(
  'name',
  'value',
))
->values(array(
  'name' => 'additional_settings__active_tab_gallery',
  'value' => 's:13:"edit-workflow";',
))
->values(array(
  'name' => 'additional_settings__active_tab_gallery_image',
  'value' => 's:12:"edit-display";',
))
->values(array(
  'name' => 'clean_url',
  'value' => 'b:1;',
))
->values(array(
  'name' => 'cron_key',
  'value' => 's:43:"X5gwvEgO9_iIqgyDQa9-of8ToTHLfcGlLAbohb05iOQ";',
))
->values(array(
  'name' => 'cron_last',
  'value' => 'i:1674979260;',
))
->values(array(
  'name' => 'css_js_query_string',
  'value' => 's:6:"rp8mul";',
))
->values(array(
  'name' => 'date_default_timezone',
  'value' => 's:3:"UTC";',
))
->values(array(
  'name' => 'drupal_private_key',
  'value' => 's:43:"G2xLIFgEUUT7wrWNet15b7Uan_awugjm_X_XjBJcixk";',
))
->values(array(
  'name' => 'field_bundle_settings_node__gallery',
  'value' => 'a:2:{s:10:"view_modes";a:3:{s:6:"teaser";a:1:{s:15:"custom_settings";b:1;}s:4:"full";a:1:{s:15:"custom_settings";b:0;}s:3:"rss";a:1:{s:15:"custom_settings";b:0;}}s:12:"extra_fields";a:2:{s:4:"form";a:1:{s:5:"title";a:1:{s:6:"weight";s:2:"-5";}}s:7:"display";a:0:{}}}',
))
->values(array(
  'name' => 'field_bundle_settings_node__gallery_image',
  'value' => 'a:2:{s:10:"view_modes";a:0:{}s:12:"extra_fields";a:2:{s:4:"form";a:1:{s:5:"title";a:1:{s:6:"weight";s:2:"-5";}}s:7:"display";a:0:{}}}',
))
->values(array(
  'name' => 'file_temporary_path',
  'value' => 's:4:"/tmp";',
))
->values(array(
  'name' => 'filter_fallback_format',
  'value' => 's:10:"plain_text";',
))
->values(array(
  'name' => 'install_profile',
  'value' => 's:7:"minimal";',
))
->values(array(
  'name' => 'install_task',
  'value' => 's:4:"done";',
))
->values(array(
  'name' => 'install_time',
  'value' => 'i:1674979260;',
))
->values(array(
  'name' => 'menu_expanded',
  'value' => 'a:0:{}',
))
->values(array(
  'name' => 'menu_masks',
  'value' => 'a:22:{i:0;i:501;i:1;i:250;i:2;i:125;i:3;i:121;i:4;i:63;i:5;i:62;i:6;i:61;i:7;i:60;i:8;i:44;i:9;i:31;i:10;i:30;i:11;i:24;i:12;i:21;i:13;i:15;i:14;i:14;i:15;i:11;i:16;i:7;i:17;i:6;i:18;i:5;i:19;i:3;i:20;i:2;i:21;i:1;}',
))
->values(array(
  'name' => 'node_options_gallery',
  'value' => 'a:2:{i:0;s:6:"status";i:1;s:7:"promote";}',
))
->values(array(
  'name' => 'node_options_gallery_image',
  'value' => 'a:1:{i:0;s:6:"status";}',
))
->values(array(
  'name' => 'node_preview_gallery',
  'value' => 's:1:"0";',
))
->values(array(
  'name' => 'node_preview_gallery_image',
  'value' => 's:1:"0";',
))
->values(array(
  'name' => 'node_submitted_gallery',
  'value' => 'i:0;',
))
->values(array(
  'name' => 'node_submitted_gallery_image',
  'value' => 'i:0;',
))
->values(array(
  'name' => 'path_alias_whitelist',
  'value' => 'a:0:{}',
))
->values(array(
  'name' => 'save_continue_gallery',
  'value' => 's:19:"Save and add fields";',
))
->values(array(
  'name' => 'site_default_country',
  'value' => 's:0:"";',
))
->values(array(
  'name' => 'site_mail',
  'value' => 's:17:"admin@example.com";',
))
->values(array(
  'name' => 'site_name',
  'value' => 's:6:"Source";',
))
->values(array(
  'name' => 'theme_default',
  'value' => 's:6:"bartik";',
))
->values(array(
  'name' => 'update_last_check',
  'value' => 'i:1674979264;',
))
->values(array(
  'name' => 'update_notify_emails',
  'value' => 'a:1:{i:0;s:17:"admin@example.com";}',
))
->values(array(
  'name' => 'user_register',
  'value' => 'i:2;',
))
->execute();

// Reset the SQL mode.
if ($connection->databaseType() === 'mysql') {
  $connection->query("SET sql_mode = '$sql_mode'");
}